### ISSUE TITLE
Błąd powyżej ~400 ocen

### ISSUE THREAD

**Issue by fizyk20** [aquz/filmweb-exporter#1]
Gdy użytkownik ma powyżej ok. 400 ocen na profilu, przeładowanie danych z widocznością ustawioną na 999999 kończy się błędem 503 - API filmweba nie wyrabia. Nie sprawdzałem, jaka dokładnie jest granica, w każdym razie przy 300 jeszcze działało.

Potencjalne rozwiązanie mogłoby być takie, żeby ustawić widoczność na 300 i przeładowywać strona po stronie. Nie wiem, na ile to jest wykonalne, ale na oko przełączanie stron jest robione AJAXem, więc powinno się dać jakoś pod to podczepić.

Pozdrawiam! :)

**Comment by lukasz-malicki-wrx** [comment]
U mnie podobnie, tyle ze gorna granica to okolo 600.
Liczymy na poprawke! ;-)

**Comment by aquz** [comment]
Zrobiłem update skryptu, sprawdźcie jak to teraz działa. Ew. jeżeli nadal coś będzie nie tak, to podajcie linki do swoich profili i ustawcie http://www.filmweb.pl/settings/privacy zeby głosy były widoczne dla wszystkich.

**Comment by lukasz-malicki-wrx** [comment]
@aquz jest ok teraz

**Comment by aquz** [comment]
Ok, dzięki za potwierdzenie.
